### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ZuoZicheng** [INK-USC/MHGRN#10]
Thanks for sharing the source code .  When I run the "preprocess.py" some error appeared .  Could you please tell me how to sovle the problem ? 
Traceback (most recent call last):
  File "D:/workspace/MHGRN/preprocess.py", line 611, in <module>
    main()
  File "D:/workspace/MHGRN/preprocess.py", line 605, in main
    rt_dic['func'](*rt_dic['args'])
  File "D:\workspace\MHGRN\utils\grounding.py", line 327, in ground
    res = match_mentioned_concepts(sents, answers, num_processes)
  File "D:\workspace\MHGRN\utils\grounding.py", line 239, in match_mentioned_concepts
    res = list(tqdm(p.imap(ground_qa_pair, zip(sents, answers)), total=len(sents)))
  File "D:\Anaconda\Anaconda\envs\krqa\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "D:\Anaconda\Anaconda\envs\krqa\lib\multiprocessing\pool.py", line 735, in next
    raise value
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ZuoZicheng** [comment]
File "D:\workspace\MHGRN\utils\grounding.py", line 101, in load_matcher
    with open(pattern_path, "r") as fin:
TypeError: expected str, bytes or os.PathLike object, not NoneType
